---
abstract: 'Cache::Memcached::Fast with sanitizing keys and fork-safe'
author:
  - 'Masahiro Nagano <kazeburo {at} gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  File::Which: 0
  Proc::Guard: 0
  Test::More: 0
  Test::Skip::UnlessExistsExecutable: 0
  Test::TCP: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Cache-Memcached-Fast-Safe
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Cache::Memcached::Fast: 0.19
  Digest::SHA: 0
  POSIX::AtFork: 0.02
  URI::Escape::XS: 0.09
  parent: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/kazeburo/Cache-Memcached-Fast-Safe.git
version: 0.01
